import test from 'node:test';
import assert from 'node:assert/strict';
import { createRandom } from '../js/random.js';
import { createClub } from '../js/data.js';
import { simulateMatch } from '../js/sim.js';
import { createLeague, createSchedule, playCurrentRound, standings, startNextSeason } from '../js/league.js';
import { createAuctionPool, createDraftPool, cpuBid } from '../js/market.js';
import { processOffseason, renewalFee, trainingSkills } from '../js/development.js';
import { exportSave, importSave } from '../js/storage.js';
import { runBatch } from '../js/batch.js';

function match(seed) { const source = createRandom(seed); const home = createClub({ id: 1, name: 'HOME', color: '#fff', seed: source }); const away = createClub({ id: 2, name: 'AWAY', color: '#000', seed: source }); return simulateMatch(home, away, createRandom(`${seed}:match:1`)); }
test('同じseedは同じ試合結果になる', () => assert.deepEqual(match('repeatable'), match('repeatable')));
test('1試合は80フェーズを完走し、初期ロスターは5人', () => { const r = match('complete'); assert.equal(r.phases, 80); assert.equal(r.playerResults.length, 10); assert.ok(r.score.home >= 0 && r.score.away >= 0); });
test('6クラブの日程は全30試合で、各クラブが10試合になる', () => { const schedule = createSchedule([1, 2, 3, 4, 5, 6]); assert.equal(schedule.length, 10); assert.equal(schedule.flatMap(r => r.fixtures).length, 30); const count = new Map([1,2,3,4,5,6].map(id => [id, 0])); schedule.flatMap(r => r.fixtures).forEach(f => { count.set(f.homeId, count.get(f.homeId) + 1); count.set(f.awayId, count.get(f.awayId) + 1); }); assert.deepEqual([...count.values()], [10,10,10,10,10,10]); });
test('リーグは10節・全30試合を完走し、順位表の勝点を正常に集計する', () => { const league = createLeague({ name: 'YOU', color: '#fff', seed: 'season' }); while (!league.completed) playCurrentRound(league); const table = standings(league); assert.equal(league.currentRound, 11); assert.equal(table.reduce((n, row) => n + row.played, 0), 60); assert.equal(table.reduce((n, row) => n + row.wins, 0), table.reduce((n, row) => n + row.losses, 0)); assert.ok(table.every(row => row.played === 10 && row.points >= 0)); });
test('市場候補は仕様数で生成され、CPU入札は資金と登録上限を超えない', () => { const league = createLeague({ name: 'YOU', color: '#fff', seed: 'market' }); const draft = createDraftPool('market'), auction = createAuctionPool('market'); assert.equal(draft.length, 24); assert.equal(auction.length, 18); const bid = cpuBid(league.clubs[1], auction[0], createRandom('bid')); assert.ok(bid >= 0 && bid <= 95); league.clubs[1].roster = Array(12).fill({}); assert.equal(cpuBid(league.clubs[1], auction[0], createRandom('full')), 0); });
test('オフシーズンは年齢・契約を進め、育成対象は選択可能な能力だけを使う', () => { const league = createLeague({ name: 'YOU', color: '#fff', seed: 'growth' }); const p = league.clubs[0].roster[0]; assert.ok(trainingSkills(p).includes('gk')); const before = p.contractYears; const result = processOffseason(league.clubs[0], new Map([[p.id, 'gk']]), createRandom('growth')); assert.equal(p.age, 26); assert.equal(p.contractYears, before - 1); assert.equal(result.length, 5); assert.ok(renewalFee(p) >= 1 && renewalFee(p) <= 20); });
test('調子・戦術・特殊能力を含む試合は能力値を恒久的に変更しない', () => { const source = createRandom('tactic'); const home = createClub({ id: 1, name: 'HOME', color: '#fff', seed: source }); const away = createClub({ id: 2, name: 'AWAY', color: '#000', seed: source }); home.tactic = 'COUNTER'; away.tactic = 'POSSESSION'; home.roster[4].specialAbility = 'フィニッシャー'; away.roster[0].specialAbility = 'ショットストッパー'; const before = JSON.stringify(home.roster.map(p => p.stats)); const result = simulateMatch(home, away, createRandom('tactic-match')); assert.equal(result.phases, 80); assert.equal(JSON.stringify(home.roster.map(p => p.stats)), before); assert.equal(Object.keys(result.forms).length, 10); });
test('10シーズンの履歴を保存して完走できる', () => { const l=createLeague({name:'YOU',color:'#fff',seed:'ten'}); for(let i=0;i<10;i++){while(!l.completed)playCurrentRound(l); startNextSeason(l);} assert.equal(l.history.length,10); assert.equal(l.history[0].table.length,6); });
test('ExportしたJSONはImportでき、不正形式は拒否する', () => { const state={league:createLeague({name:'YOU',color:'#fff',seed:'save'})}; assert.equal(importSave(exportSave(state)).league.seed,'save'); assert.throws(()=>importSave('{}')); });
test('バッチ検証は100リーグを完走し、集計値を返す', () => { const r=runBatch(100); assert.equal(r.leagues,100); assert.equal(r.matches,3000); assert.ok(r.averageGoals>0 && r.drawRate>=0 && r.drawRate<=1); });
